# lambda-template/.github/workflows/deploy.yml
permissions:
  id-token: write      # needed for STS AssumeRoleWithWebIdentity
  contents: read       # so checkout can pull your code

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: acs-lambda/.github/.github/workflows/deploy-lambda.yml@main
    with:
      function-name: aws-lambda-function-name-here   # ‚Üê Change this to the AWS Lambda Function Name!
      region: us-east-2                 # optional
